spring:
  application:
    name: cache.svc
  cloud:
    aws:
      region:
        static: ap-south-1
      

aws:
  servicediscovery:
    namespace:
      name: nisran.local
      vpc-id: vpc-0503be314e240016e

server:
  port: 8080

router:
  virtual-nodes-per-server: 1
  router-refresh-interval-seconds: 3000

cache:
  capacity: 100
  service:
    discovery:
      enabled: true
      heartbeat-interval: 300000
      deregister-interval: 100000

logging:
  level:
    root: INFO
    nisran.router: DEBUG
    nisran.controller: DEBUG
    software.amazon.awssdk: INFO