spring:
  application:
    name: cache-cluster-service
  cloud:
    aws:
      region:
        static: ap-south-1
      

aws:
  servicediscovery:
    namespace:
      name: cache-service-internal:local
      vpc-id: vpc-0503be314e240016e

server:
  port: 8080

cache:
  capacity: 100
  service:
    discovery:
      enabled: true
      heartbeat-interval: 30000
      deregister-interval: 100000

logging:
  level:
    root: INFO
    nisran: DEBUG
    software.amazon.awssdk: DEBUG 