spring:
  application:
    name: cache-service
  cloud:
    aws:
      region:
        static: ap-south-1
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      stack:
        auto: false
      discovery:
        enabled: true
      parameter-store:
        enabled: true
        prefix: /config
        name: cache-service
      sqs:
        enabled: true

server:
  port: 8080

cache:
  capacity: 100
  service:
    discovery:
      enabled: true
      heartbeat-interval: 3000
      deregister-interval: 6000

logging:
  level:
    root: INFO
    nisran: DEBUG 